name: Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountID: ${{ secrets.CF_ACCOUNT_ID }}
          secrets: |
            database_id
          env:
            database_id: ${{ secrets.D1_DATABASE_ID }}